# Generated by Django 5.0 on 2023-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicName', models.CharField(max_length=240, null=True)),
                ('coordinatorName', models.CharField(default='0', max_length=240)),
                ('email', models.CharField(max_length=240, null=True)),
                ('phone', models.CharField(max_length=240, null=True)),
                ('seatCount', models.CharField(max_length=240, null=True)),
                ('username', models.CharField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240)),
            ],
        ),
    ]
