# Generated by Django 5.0 on 2023-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_academic_db_academicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_db',
            name='saveDate',
            field=models.DateTimeField(max_length=240, null=True),
        ),
    ]
