# Generated by Django 5.0 on 2023-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_academic_db_savedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBasic_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_is', models.CharField(max_length=240, null=True)),
                ('value_is', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
