# Generated by Django 5.0 on 2023-12-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegistration_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=240, null=True)),
                ('lastName', models.CharField(max_length=240, null=True)),
                ('dateofbirth', models.DateField(default='0', max_length=240)),
                ('gender', models.CharField(max_length=240, null=True)),
                ('email', models.CharField(max_length=240, null=True)),
                ('phone', models.CharField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('qualification', models.CharField(max_length=240, null=True)),
                ('course', models.CharField(max_length=240, null=True)),
                ('parentName', models.CharField(max_length=240, null=True)),
                ('contactNumber', models.CharField(max_length=240, null=True)),
                ('saveDate', models.DateTimeField(max_length=240, null=True)),
                ('status', models.CharField(default='0', max_length=240)),
            ],
        ),
    ]
