# Generated by Django 5.0 on 2023-12-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_user', '0002_userregistration_db_enrolmentno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration_db',
            name='dateofbirth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration_db',
            name='lastName',
            field=models.CharField(max_length=240),
        ),
    ]
